### PR TITLE
Update database initialization and sync logic; fix failure to update bank account name/currency

### PR DESCRIPTION
**Pull request by dichiara19**
- Modified 'dateCreated' and 'dateTimeModified' in 'TransactionWallet' to use a single timestamp.
- Enhanced 'FinanceDatabase' with new methods for merging and syncing wallet data, ensuring proper updates based on modification timestamps.

### CODE REVIEW

**Comment by jameskokoska** [comment]
I’m a little unsure what this is trying to accomplish. Syncing of accounts/wallets is already supported within Cashew. Additionally, please view the README about contributions - I will still go through each PR for change recommendations however but I’m not sure how these changes fix or add to any functionality.

**Comment by dichiara19** [comment]
Hello,

I realized that there are differences in synchronization between the
modified accounts in mobile and the web app this because the first account
created turns out to have a timestamp on which the synchronization does not
intervene. in fact despite having changed the name and the currency from
mobile only the amount is synchronized cross device


Il Lun 30 Dic 2024, 19:59 James ***@***.***> ha scritto:

**Comment by jameskokoska** [comment]
The account should automatically be synced since the modified timestamp will be updated every time it is changed. The sync algorithm already considers the latest modified timestamp when updating changes. Is this currently not happening?

**Comment by dichiara19** [comment]
I'm sending you screenshots of examples between web apps on PC and Android
app:
this is on PC:
[image: image.png]

Il Lun 30 Dic 2024, 23:48 James ***@***.***> ha scritto:

**Pull request closed without merging**
